# syntax=docker/dockerfile:1.7

ARG GO_VERSION={{ .GoVersion }}
ARG ALPINE_VERSION=3.20

FROM golang:${GO_VERSION}-alpine${ALPINE_VERSION} AS builder
WORKDIR /src

RUN apk add --no-cache git ca-certificates tzdata

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download

COPY . .
ARG VERSION=dev
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux \
    go build -trimpath \
      -ldflags="-s -w -X {{ .ModulePath }}/internal/buildinfo.Version=${VERSION}" \
      -o /out/{{ .BinaryName }} ./cmd/{{ .BinaryName }}

FROM gcr.io/distroless/static-debian12:nonroot AS runtime
WORKDIR /
COPY --from=builder /out/{{ .BinaryName }} /{{ .BinaryName }}
USER nonroot:nonroot
EXPOSE 8080{{ if .GRPC }} 9090{{ end }}
ENTRYPOINT ["/{{ .BinaryName }}"]
